name: WordPress PHP Linting with PHP Code Sniffer

on:
  push:
    branches:
      - php8.2_linting
  pull_request:
    branches:
      - development

jobs:
  lint-wordpress-php:
    name: Run WordPress PHP Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          coverage: none
          tools: phpcs

      - name: Allow Codesniffer composer installer
        run: composer global config --no-plugins allow-plugins.dealerdirect/phpcodesniffer-composer-installer true

      - name: Install WordPress Coding Standards
        run: composer global require wp-coding-standards/wpcs

      - name: Run WordPress PHP Linter
        run: phpcs --standard=WordPress --extensions=php --ignore=*.js,*.css .
